### ISSUE TITLE
Step 4 issue

### ISSUE THREAD

**Issue by DatSplit** [Beastwick18/jetson-orin-nano-nvme-sdkmanager-setup#1] opened 2024-12-03 01:09 UTC
Thanks for the guide. I'm currently stuck at the end of step 4:
![image](https://github.com/user-attachments/assets/4101ffd3-3c9f-455a-83f5-0071116edfa1)
![image](https://github.com/user-attachments/assets/2bff0b31-93e4-4df7-8db7-c60c9411ba92)

If you feel like helping me I'd appreciate that.
Maybe I should just buy a Linux mini-pc, because as you mentioned this is horrible.

**Comment by Beastwick18** [comment] 2024-12-03 20:07
I don't think this was an error I encountered when setting things up. It may be related to usbipd.exe not sharing the USB or losing access to it. From looking at some forums where people had similar errors, it seems like it could be a few other things too.

1. Make sure you're flashing Jetpack 5.1.2, as others had this issue with version 6+
2. Try using a different version of Ubuntu, like 18.04
3. Try the steps here: https://nvidia-jetson.piveral.com/jetson-orin-nano/error-usb-write-timeout-during-jetson-orin-nano-dev-board-flashing/

Some links:
https://forums.developer.nvidia.com/t/error-might-be-timeout-in-usb-write/254513
https://www.reddit.com/r/JetsonNano/comments/197b9sy/jetson_orin_flashing_error/

Unfortunately, I no longer have access to a Jetson to try and reproduce this, and it's been quite a while since I had used it. Ultimately, the solution I reached to get this working is untested on others machines/hardware.

If you have a spare hard drive or laptop laying around, you could use that for installing Linux on and trying to install from there. You could also try running Linux from a USB. Running a Linux installer on a USB is almost enough, but installed programs, settings, etc. will not persist between reboots, which is annoying. So if you have 2 USBs you might put the Ubuntu 18.04/20.04 installer on one USB, and perform a full installation onto the second USB, then boot from the second one. This should allow persistent storage.

**Comment by DatSplit** [comment] 2024-12-03 22:54
Thanks a lot for your elaborate response!

1. Still causes the issue for me.
2. Ubuntu 18.04 causes the same issue.
3. The potential solutions provided also did not work.

I've also read that adding a MicroSD can potentially fix this issue: (https://www.reddit.com/r/JetsonNano/comments/197b9sy/jetson_orin_flashing_error/?rdt=48414)

Might try that as well.
Will update you whether that works.

**Comment by DatSplit** [comment] 2024-12-10 08:50
@Beastwick18 Dual-booted a laptop with Ubuntu 22.04 and the flash process was smooth sailing.
Quite frankly, NVIDIA should add a clear disclaimer that WSL flashing is not stable at all (https://docs.nvidia.com/sdk-manager/wsl-systems/index.html).
Anyway, thanks a lot for creating this repository and I wish you all the best in your studies and/or professional career!

**Comment by Beastwick18** [comment] 2024-12-11 02:44
Awesome, I'll go ahead and close this. Glad to hear you got it working, and thanks for the kind words!

**Closed as completed by Beastwick18** 2024-12-11 02:44 UTC
